<?php

namespace Puzzle\ExpertiseBundle\Repository;

use Puzzle\AdminBundle\Repository\PuzzleRepository;

/**
 * FaqRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FaqRepository extends PuzzleRepository
{
}
